modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="terrain_diffusion_mc"
namespace="terrain-diffusion-mc"
version="${version}"
displayName="Terrain Diffusion MC"
description='''Terrain Diffusion in Minecraft.'''

[[mixins]]
config="terrain-diffusion-mc.mixins.json"

[[mixins]]
config="terrain-diffusion-mc.client.mixins.json"

[[dependencies.terrain_diffusion_mc]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.terrain_diffusion_mc]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="BOTH"
